name: "Unit Tests"
on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  run-tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Tox Cache
      id: cache-tox
      uses: actions/cache@v3
      with:
        path: .tox
        # setup.cfg and pyproject.toml have versioning info that would
        # impact the tox environment.
        key: tox-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
    - name: Test with tox
      run: tox
